export enum Genre {
    SCIENCE_FICTION = "Ficção Científica",
    FANTASY = "Fantasia",
    ROMANCE = "Romance",
    SUSPENSE = "Suspense",
    MYSTERY = "Mistério",
    HORROR = "Terror",
    ADVENTURE = "Aventura",
    HISTORY = "História",
    BIOGRAPHY = "Biografia",
    SELF_HELP = "Autoajuda",
    POETRY = "Poesia",
    CLASSIC_LITERATURE = "Literatura Clássica",
    CONTEMPORARY_LITERATURE = "Literatura Contemporânea",
    YOUNG_ADULT = "Jovem Adulto",
    CHILDRENS = "Infantil",
    NON_FICTION = "Não Ficção",
    ESSAYS = "Ensaios",
    CHRONICLES = "Crônicas",
    DRAMA = "Drama",
    HUMOR = "Humor"
}